module.exports = {
  extends: [
    'eslint:recommended',
    'plugin:import/recommended',
  ],

  env: {
    es2021: true,
    node: true,
    browser: true,
  },

  rules: {
    'import/no-unresolved': 0,

    'array-bracket-spacing': 2,
    'arrow-spacing': 2,
    'block-spacing': 2,
    'brace-style': [2, '1tbs', { allowSingleLine: true }],
    'comma-dangle': [2, 'only-multiline'],
    'comma-spacing': 2,
    'computed-property-spacing': 2,
    'dot-location': [2, 'property'],
    'dot-notation': 2,
    'eol-last': 2,
    eqeqeq: 2,
    'for-direction': 2,
    'func-call-spacing': 2,
    'generator-star-spacing': [2, 'after'],
    indent: [2, 2, { SwitchCase: 1 }],
    'keyword-spacing': 2,
    'key-spacing': 2,
    'linebreak-style': 2,
    'lines-between-class-members': [2, 'always', { exceptAfterSingleLine: true }],
    'multiline-ternary': [2, 'never'],
    'no-alert': 2,
    'no-console': 2,
    'no-empty': [2, { allowEmptyCatch: true }],
    'no-lone-blocks': 2,
    'no-lonely-if': 2,
    'no-multiple-empty-lines': [2, { max: 1, maxBOF: 0, maxEOF: 0 }],
    'no-multi-spaces': 2,
    'no-new-wrappers': 2,
    'no-return-await': 2,
    'no-self-compare': 2,
    'no-tabs': 2,
    'no-trailing-spaces': 2,
    'no-unneeded-ternary': 2,
    'no-unused-vars': 2,
    'no-useless-concat': 2,
    'no-var': 2,
    'no-void': 2,
    'no-whitespace-before-property': 2,
    'object-curly-spacing': [2, 'always'],
    'prefer-template': 2,
    'quote-props': [2, 'as-needed'],
    quotes: [2, 'single'],
    'require-await': 2,
    'rest-spread-spacing': 2,
    semi: [2, 'never', { beforeStatementContinuationChars: 'never' }],
    'semi-style': [2, 'last'],
    'space-before-blocks': 2,
    'space-before-function-paren': [2, { named: 'never', anonymous: 'never' }],
    'space-infix-ops': 2,
    'space-in-parens': 2,
    'switch-colon-spacing': 2,
    'template-curly-spacing': 2,
  },
}
